### PR TITLE
[Cassandra] removed tracing from insert

### PR DESCRIPTION
**Pull request by Mike-Petersen**
Hi,
i removed the tracing from the insert statement cause it had a severe impact in performance.

Was there a reason for that or was i just left accidentally in the code?

Regards
Mike

### CODE REVIEW

**Comment by busbey** [comment]
Could you isolate this PR to just the Cassandra issue?

**Comment by cmccoy** [comment]
Definitely accidentally left. Other than @busbey's comment, :+1:. We should pull this into v0.6.0.

**Comment by Mike-Petersen** [comment]
I have isolated the cassandra issue

**Comment by bigbes** [comment]
@cmccoy let's merge it, then?

**Comment by cmccoy** [comment]
Sounds good.

**Comment by busbey** [comment]
Thanks for the improvement!

**Pull request merged**
