### PR TITLE
[hbase10] Skip HBase MiniCluster tests on Windows

### LINKED ISSUE #434: Building hbase10 bindings on windows fails in test phase
building on windows fails during the test phase while attempting to run the new-in-0.4.0 hbase 1.0+ tests.

Attaching the tail end of the log with the unsatisfied link error in hadoop.
[ycsb-0.4.0-rc2-failure-hbase10.txt](https://github.com/brianfrankcooper/YCSB/files/12404/ycsb-0.4.0-rc2-failure-hbase10.txt)

### PR DESCRIPTION
**Pull request by cmccoy**
I believe this should fix #434.

### CODE REVIEW

**Comment by busbey** [comment]
looks good. I can test on a windows machine tonight if no one else has one. (I'm in the office today, so  I can't reach it.)

**Comment by cmccoy** [comment]
If you're willing, that would be great. Thanks.

**Comment by busbey** [comment]
worked great on windows.

**Comment by cmccoy** [comment]
Thanks for testing & merging.

**Pull request merged**
