### PR TITLE
Declarations should use Java collection interfaces such as "List" rather than specific implementation classes such as "LinkedList"

### PR DESCRIPTION
**Pull request by kirill-vlasov**
This pull request is focused on resolving occurrences of Sonar rule squid:S1319 - Declarations should use Java collection interfaces such as "List" rather than specific implementation classes such as "LinkedList"
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1319
Please let me know if you have any questions.
Kirill Vlasov

### CODE REVIEW

**Comment by busbey** [comment]
This looks good to me. I'd like to merge #552 first, since I think this will cause that patch to fail to apply.

**Comment by busbey** [comment]
We'll need to flag this as an incompatible change for datastore binding implementations.

**Comment by busbey** [comment]
Please rebase for current master and update commit message for changed modules. Otherwise looks good.

**Comment by risdenk** [comment]
Would be awesome to update this. Its a simple change but affects a lot of files.

**Comment by risdenk** [comment]
@manolama - Here is an existing PR for what you were talking about going HashMap -> Map.

**Comment by manolama** [comment]
Cleaned up and merged in cf5d2ca5f554fe721e7924a92ca5e5a6e0cdf8ce. I'll make a note about the signature change for binding implementors in the release notes.

**Pull request closed without merging**
