### PR TITLE
[release] Update README for the release of YCSB 0.14.0

### PR DESCRIPTION
**Pull request by busbey**

### CODE REVIEW

**Comment by dorlaor** [comment]
Awesome! Btw - was the tgz file always that big - 625MB ?

**Comment by busbey** [comment]
the 0.12.0 release was 329MiB. 0.13.0 didn't have convenience tarballs since it was flagged as not-ready-for-production, but it would have been 396MiB. I expect the next release will be significantly smaller as we peel off several deprecated bindings.

**Comment by busbey** [comment]
BTW, is it safe to take that as a "this looks fine to merge"?

**Comment by dorlaor** [comment]
+1 looks fine and works

**Pull request merged**
