### PR TITLE
Updated for Hypertable version 0.9.7.12; Performance improvements

### PR DESCRIPTION
**Pull request by nuggetwheat**
Hi Brian,

I'm the maintainer of Hypertable.  I've updated the Hypertable YCSB driver for the latest stable version of Hypertable (0.9.7.12).  I also made a number of performance improvements to the driver and updated the README.  Can you please pull in this commit?  Thank you!
- Doug

### CODE REVIEW

**Comment by busbey** [comment]
Hiya @nuggetwheat sorry for the lag. Care to  update this to current stable before I merge it?

**Comment by nuggetwheat** [comment]
Hi Sean,

Sure, no problem.  I can do that this week.  If you have a release deadline
for this, just let me know what it is and I'll try to get it finished by
then.

- Doug

**Comment by busbey** [comment]
I'm aiming to start a monthly release cadence in a week or two, so this week should be plenty fast.

Thanks!

**Comment by busbey** [comment]
FYI, #266 is now tracking our next release. We'll start release candidate testing in mid-June. At that point we'll be feature frozen, so if things come in after they'll go towards the following release (which hopefully will go into resting mid-July).

**Comment by busbey** [comment]
Bump. Any update here?

**Comment by risdenk** [comment]
@nuggetwheat are the performance improvements from this PR still valid? It looks like they were addressed along the way. The driver version was never updated though.

**Comment by busbey** [comment]
the docs updates seem needed still as well.

**Comment by busbey** [comment]
Given [the closing of the hypertable support company](http://www.hypertable.com/blog/hypertable_inc._is_closing_its_doors) we might be waiting a while here.

Presuming the project is still on-going, I'm fine with being patient.

**Comment by busbey** [comment]
hypertable never made it out as a project independent of the company, AFAICT.

happy for a reopen if someone determines otherwise.

**Pull request closed without merging**
