### PR TITLE
[core] Add the NumericByteIterator for dealing with numeric values.

### PR DESCRIPTION
**Pull request by manolama**
Add a .reset() method to the ByteIterator class and subclasses so
that unit tests can implement a single set of iterators and re-use
them if necessary.

### CODE REVIEW

**Comment by manolama** [comment]
Back to work on https://github.com/brianfrankcooper/YCSB/issues/653.

**Comment by risdenk** [comment]
@manolama can you help review any of the following? They will probably conflict a bit but it would at least get the style under control for the core module.
* #901 
* #900 
* #899 
* #898 
* #897 
* #896

**Comment by manolama** [comment]
Sure thing :)

**Comment by risdenk** [comment]
looks like the failure is related:
```
com.yahoo.ycsb.db.AsyncMongoDbClient.BinaryByteArrayIterator is not abstract and does not override abstract method reset() in com.yahoo.ycsb.ByteIterator
```

**Comment by risdenk** [comment]
@manolama all the checkstyle changes for core are in now #895 so you should be good to go on this change.

**Comment by risdenk** [comment]
@manolama - just a ping on this if you were planning to update it?

**Comment by manolama** [comment]
Forgot I had this one. I'll separate it out into a separate PR.

**Pull request closed without merging**
