### PR TITLE
[client] Added basic command line argument error messages to Client.java

### PR DESCRIPTION
**Pull request by petergaultney**
This stems from my earlier adventures (see #407) trying to get a basic MySQL benchmark to run over JDBC, and improperly supplying the classpath but having no way to know what was upsetting the Java command line argument parser.

also "fixed" some indentation, because the alternative would have been to submit poorly indented code. Emacs is great for keeping indentation consistent, but if you're trying to match a file that isn't consistent, you're pretty much screwed. :)

### CODE REVIEW

**Comment by busbey** [comment]
please write the messages to stderr.

nit, but if you're sufficiently familiar with git, could you update the commit message to start with "[client]"?

**Comment by busbey** [comment]
wait, we exit with status 0 (aka "Success") in all these cases? That sounds wrong to me. anyone else?

**Comment by cmatser** [comment]
Exit status 0 in all cases is wrong, but I don't think you're asking @petergaultney to fix that.  Right?  :)

**Comment by petergaultney** [comment]
I completely agree that it's wrong, but didn't feel comfortable making any decisions about whether to go with -1 or a series of different negative integers. 

I always need to learn more git, so I can certainly make the commit message start with [client] once I figure it out.

While I'm at it, shall I just change the errors I'm touching to -1 and let someone else decide whether to make it more granular than that?

**Comment by busbey** [comment]
I just wanted to make sure I wasn't missing something obvious before introducing an incompatible change.

Peter,  I'm fine with you leaving the exit codes as are. If you're up for updating all of them to be -1 (or really any other non-zero number), that'd be great.

If this commit is the last one on the branch, you can edit the message easily by using `git commit --amend`.

While you're updating the git commit, could you break this into two patches? First one that fixes the formatting and then one with the change of functionality? (Let me know if you'd like help in how to break a commit into two.)

**Comment by busbey** [comment]
Bump. I'd like to get this in soon.

@petergaultney think you'll have time to revisit this in the new year?

**Comment by busbey** [comment]
@petergaultney, could you ammend the commit message? We'll take care of the other nits in a follow-on PR

**Comment by risdenk** [comment]
@busbey - Any thoughts about getting this into 0.7.0? #624

**Comment by busbey** [comment]
yeah, sure.

**Pull request merged**
