### PR TITLE
[tarantool] Update tarantool driver version

### PR DESCRIPTION
**Pull request by bigbes**

### CODE REVIEW

**Comment by busbey** [comment]
The Travis failure is from the kudu change. I merged that fix, but this change will have to get rebased before Travis will include it when testing this change.

**Comment by bigbes** [comment]
@busbey I've rebased it, CI passed.

**Comment by busbey** [comment]
+1

**Comment by bigbes** [comment]
let's merge it and create RC1?

**Comment by busbey** [comment]
Yep. Sounds good to me!

**Pull request merged**
