### PR TITLE
[PostgreNoSQL] Added NoSQL support for PostgreSQL.

### PR DESCRIPTION
**Pull request by leschekhomann**
@busbey: I hope to have addressed all suggested adaptions.
- Removed package information from testing.
- Added caching for the SQL Statements by using the Statement Class.
- Added additional information about code changes in the license part.
- Simplified test code (removed creation and deletion of test database, only use travis).

### CODE REVIEW

**Comment by leschekhomann** [comment]
@busbey: Any news here?

**Comment by busbey** [comment]
Thanks for the reminder. I was originally going to try to close out a release before merging this, but that didn't happen. I'll try to get a review done soon.

**Comment by leschekhomann** [comment]
@busbey: Thanks for the quick response and your time to review the pull request.

**Comment by leschekhomann** [comment]
One additional information: Maybe it is useful to remove the **padded** and **createFieldSet** methods from the **PostgreNoSQLDBClientTest** as they are also implemented in other YCSB bindings. Somewhere in the core?

**Comment by leschekhomann** [comment]
Hi @busbey. Any news here? Best regards

**Comment by busbey** [comment]
I thought I merged this already. Sorry!

I'll take a look during my block of open source time tomorrow.

**Comment by leschekhomann** [comment]
Hi @busbey. No problem. Thanks for checking the pull request. Please check my comments above and in the code. There are some things I am not sure about, for instance, reusing code of other bindings of the YCSB project.

**Comment by leschekhomann** [comment]
As you can see in the license notes of the sources some of the code is based on the jdbc binding.

**Comment by leschekhomann** [comment]
Hi @busbey. Any news?

**Comment by leschekhomann** [comment]
@busbey: Thanks for accepting the pull request. How about my comments regarding the license and source code adoptions? Everything fine so far?

**Comment by busbey** [comment]
Yeah that's fine. We can always try to deduplicate later.

**Pull request merged**
