### PR TITLE
Update cassandra2-cql driver to only run tests on jdk8

### PR DESCRIPTION
**Pull request by busbey**
update the work in #614 so that maven skips tests under jdk7 and uses a profile to turn them on under jdk8.

### CODE REVIEW

**Comment by risdenk** [comment]
Looks good to me. Didn't get to test it on JDK 8 though.

**Comment by busbey** [comment]
I could add the travis-ci change to test jdk8 now, if it would help?

**Comment by risdenk** [comment]
:+1: sorry @busbey took me a few days to get back to this.

**Comment by busbey** [comment]
No worries. Is the thumbs up for merging as-is or for adding the travis-ci change?

**Comment by risdenk** [comment]
merge. I think the travis ci change should be separate.

**Comment by risdenk** [comment]
Just as a note: this prints a really "scary" message about sigar on Mac when trying to test with JDK 8. The warning doesn't cause any issues and the tests pass just fine. An example of the message is here:

```
no libsigar-amd64-linux.so in java.library.path
org.hyperic.sigar.SigarException: no libsigar-amd64-linux.so in java.library.path
        at org.hyperic.sigar.Sigar.loadLibrary(Sigar.java:172)
        at org.hyperic.sigar.Sigar.<clinit>(Sigar.java:100)
        at org.apache.cassandra.utils.SigarLibrary.<init>(SigarLibrary.java:47)
        at org.apache.cassandra.utils.SigarLibrary.<clinit>(SigarLibrary.java:28)
        at org.apache.cassandra.service.StartupChecks$6.execute(StartupChecks.java:197)
        at org.apache.cassandra.service.StartupChecks.verify(StartupChecks.java:106)
        at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:169)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:551)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:125)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Pull request merged**
