### PR TITLE
[core] Fix #380 by working around recorder/logger initialization timing.

### LINKED ISSUE #380: [core] HdrHistogram logs are cannot be partially processed by HistogramLogProcessor
See https://github.com/HdrHistogram/HdrHistogram/issues/69
This issue with the HistogramLogReader/Writer interaction means that the histogram logs produced by YCSB cannot be processed correctly when the '-end' and '-start' options are used.

### PR DESCRIPTION
**Pull request by nitsanw**
The HdrHistogramReader makes some problematic assumptions on the roles played by start time, base time and histogram start/end times. This is to be revisited in a future release of HdrHistogram (see HdrHistogram/HdrHistogram#69). In the meantime this change will make YCSB record as expected by the current reader:
a. Set histogram log base time (same as start time)
b. Only create the recorder after the log has been setup

### CODE REVIEW

**Comment by busbey** [comment]
could you redo the commit message to start the first line with "[core]"?

**Comment by busbey** [comment]
could you amend to leave out the formatting changes?

**Comment by nitsanw** [comment]
Learned a new git trick in the process ;)
Thanks

**Comment by busbey** [comment]
Thanks!

**Pull request merged**
