### PR TITLE
add firestore binding

### PR DESCRIPTION
**Pull request by flint-dominic**
this is using the standard firestore library and implements all actions.

### CODE REVIEW

**Comment by risdenk** [comment]
@flint-dominic issue isn't with Maven repository location. Looks like there are version conflicts. 

In the output below, "Could not resolve version conflict among". You would need to parse this and look to see which dependencies are conflicting. It looks like `io.grpc:grpc-core:jar:1.14.0` to me.

```
[[1;31mERROR[m] Failed to execute goal on project [36mycsb[m: [1;31mCould not resolve dependencies for project com.yahoo.ycsb:ycsb:pom:0.16.0-SNAPSHOT: Failed to collect dependencies for com.yahoo.ycsb:ycsb:pom:0.16.0-SNAPSHOT[m: Could not resolve version conflict among [com.yahoo.ycsb:cloudspanner-binding:jar:0.16.0-SNAPSHOT -> com.google.cloud:google-cloud-spanner:jar:0.24.0-beta -> com.google.cloud:google-cloud-core-grpc:jar:1.6.0 -> io.grpc:grpc-protobuf:jar:1.6.1 -> io.grpc:grpc-core:jar:1.6.1, com.yahoo.ycsb:cloudspanner-binding:jar:0.16.0-SNAPSHOT -> com.google.cloud:google-cloud-spanner:jar:0.24.0-beta -> com.google.cloud:google-cloud-core-grpc:jar:1.6.0 -> io.grpc:grpc-protobuf:jar:1.6.1 -> io.grpc:grpc-protobuf-lite:jar:1.6.1 -> io.grpc:grpc-core:jar:1.6.1, com.yahoo.ycsb:cloudspanner-binding:jar:0.16.0-SNAPSHOT -> com.google.cloud:google-cloud-spanner:jar:0.24.0-beta -> io.grpc:grpc-netty:jar:1.6.1 -> io.grpc:grpc-core:jar:[1.6.1,1.6.1], com.yahoo.ycsb:cloudspanner-binding:jar:0.16.0-SNAPSHOT -> com.google.cloud:google-cloud-spanner:jar:0.24.0-beta -> io.grpc:grpc-auth:jar:1.6.1 -> io.grpc:grpc-core:jar:[1.6.1,1.6.1], com.yahoo.ycsb:cloudspanner-binding:jar:0.16.0-SNAPSHOT -> com.google.cloud:google-cloud-spanner:jar:0.24.0-beta -> io.grpc:grpc-stub:jar:1.6.1 -> io.grpc:grpc-core:jar:1.6.1, com.yahoo.ycsb:googlebigtable-binding:jar:0.16.0-SNAPSHOT -> com.google.cloud.bigtable:bigtable-hbase-1.x:jar:1.3.0 -> com.google.cloud.bigtable:bigtable-hbase:jar:1.3.0 -> com.google.cloud.bigtable:bigtable-client-core:jar:1.3.0 -> io.grpc:grpc-core:jar:1.10.0, com.yahoo.ycsb:googlebigtable-binding:jar:0.16.0-SNAPSHOT -> com.google.cloud.bigtable:bigtable-hbase-1.x:jar:1.3.0 -> com.google.cloud.bigtable:bigtable-hbase:jar:1.3.0 -> io.grpc:grpc-core:jar:1.10.0, com.yahoo.ycsb:googlefirestore-binding:jar:0.16.0-SNAPSHOT -> com.google.cloud:google-cloud-firestore:jar:0.81.0-beta -> io.grpc:grpc-netty-shaded:jar:1.18.0 -> io.grpc:grpc-core:jar:[1.18.0,1.18.0], com.yahoo.ycsb:googlefirestore-binding:jar:0.16.0-SNAPSHOT -> com.google.cloud:google-cloud-firestore:jar:0.81.0-beta -> io.opencensus:opencensus-contrib-grpc-util:jar:0.18.0 -> io.grpc:grpc-core:jar:1.14.0] ->
```

**Comment by flint-dominic** [comment]
ah got it, so i need to find a version that works with io.grpc:grpc-core:jar:1.6.1 from the old version used by spanner?

**Comment by risdenk** [comment]
Potentially. Not really sure :) The output should say what the dependency chain is.

**Comment by flint-dominic** [comment]
ill remove this until i can figure out which sub-package isn't compatible and still works.  thanks!

**Comment by flint-dominic** [comment]
the spanner one is 2 years old, we want that to be the gold standard?  i think firestore was just released around then....

**Comment by risdenk** [comment]
It might be the case of bumping spanner. You could leave this open doesn't hurt anything in the mean time.

**Pull request closed without merging**
