### PR TITLE
Added Support For Google Firestore

### PR DESCRIPTION
**Pull request by 88sanjay**
* Added client support for google firestore.
* Updated versions of conflicting google projects
* Updated Readme for configuring the firestore client.

### CODE REVIEW

**Comment by 88sanjay** [comment]
Any idea why the last test case is failing ? I do not see any issue with the code .

**Comment by busbey** [comment]
looks like it might just be transient. I restarted that part of the build.

**Comment by 88sanjay** [comment]
@busbey - Thanks. Do you know who can review my PR ?

**Comment by sxlijin** [comment]
This PR should be closed in favor of #1320.

**Pull request closed without merging**
