### PR TITLE
[aerospike] Checkstyle updates for Aerospike.

### PR DESCRIPTION
**Pull request by allanbank**
* Added a package-info.java.
* Added JavaDoc for the binding's DB implementation.

### CODE REVIEW

**Comment by cmccoy** [comment]
+1

**Comment by kruthar** [comment]
@allanbank did you have this similar fix in the works for the JDBC module? If not I'll go ahead and replicate, just didn't want to duplicate effort if you were on it already. I have been working in the JDBC module and have a few other issues to take care of. Besides checkstyle enforcement being 'the right thing to do', currently the indentation is terrible and it's unpleasent to work in.

**Comment by cmccoy** [comment]
(jumping in): would you mind waiting on #469, which touches a lot of bindings?

**Comment by kruthar** [comment]
Oh ya! Forgot to say I knew you were working on #469 and was def gonna wait for that one. I checked the other PRs and it looks like the only other relevant one that would touch the JDBC binding is #447. Pretty sure I have already caused conflicts in that one with another PR, either way the merge should not be super difficult.

**Comment by allanbank** [comment]
@kruthar - Yes just drop the blob into the pom and work down the issues.  I have a Eclipse formatter to do most of the white-space fixes if you would like it.

**Comment by kruthar** [comment]
@allanbank - thanks for the suggestion, but I'm an Intellij kinda guy myself. I'll add the same checkstyle enforcement you did and just shoot down the issues until we're good to go.

**Pull request merged**
