### PR TITLE
[geode] Update geode binding for v1.0.0-incubating.M2

### PR DESCRIPTION
**Pull request by metatype**

### CODE REVIEW

**Comment by busbey** [comment]
Please prefix commit messages with the kmpacted module, i.e. "[geode]"

**Comment by busbey** [comment]
Can an M2 client talk to an M1 server?

**Comment by metatype** [comment]
@busbey The geode project isn't guaranteeing backwards compatibility between the M# releases, but in this case a quick test with an M2 client / M1 servers works.

Thanks for taking a look at this change!

**Comment by busbey** [comment]
bump. I'd like to get this merged soon, could you update the commit message please?

**Comment by metatype** [comment]
Just updated the commit message.

**Comment by busbey** [comment]
thanks!

**Pull request merged**
