### PR TITLE
Support for configurable fractional percentile metrics in output file...

### PR DESCRIPTION
**Pull request by jschmieg**
I added support for Double values in percentile metrics. Configuration is not changed: values are defined in hdrhistogram.percentiles, but with this modification, it accepts Double values.

### CODE REVIEW

**Comment by risdenk** [comment]
@jschmieg is this a duplicate of PR #862?

**Comment by jschmieg** [comment]
Yes,it is. I requested it again to see Travis build status, which failed at first time.

**Comment by risdenk** [comment]
ok just closed #862. We can focus on this PR. I can take a look at the failing travis ci tests.

**Comment by risdenk** [comment]
@jschmieg Does this change the output format for integers? If you put in say 95 will it output 95.0?

**Comment by jschmieg** [comment]
Hi @risdenk , 
it doesn't change format of integers. They still look like this:
`[INSERT], 95thPercentileLatency(us), 700.0`
For double values output is like this:
`[INSERT], 99.9PercentileLatency(us), 18415.0`

**Comment by risdenk** [comment]
Thanks @jschmieg

**Pull request merged**
