### PR TITLE
[core] Fix ycsb.sh and ycsb.bat missing core dependencies

### LINKED ISSUE #877: ycsb.sh and ycsb.bat don't work from source checkout
The core dependencies aren't added to the classpath when bindings are used.

### PR DESCRIPTION
**Pull request by risdenk**
Fixes #877.

I don't know if this is the best way to solve this. Basically the core module's parent was root before. I made it binding parent so that it will pickup the necessary assembly plugin and create the lib directory. I'm not really familiar with Maven module parents and dependencies.

### CODE REVIEW

**Comment by risdenk** [comment]
@busbey - Sorry to keep bugging you with reviews. Not sure who else would know how this should work. If there is someone else to ping let me know.

**Comment by busbey** [comment]
sorry I lost track of this one.

> @busbey - Sorry to keep bugging you with reviews. Not sure who else would know how this should work. If there is someone else to ping let me know.

Might be time to bring in some additional project maintainers.

I don't think adding binding-parent to be the core's parent is the right way to do this. I'm trying to grok the underlying problem reading a few of the referenced problems.

Is it just when using a source checkout and a binding other than the built-in dummy one?

**Comment by noahdesu** [comment]
I'm seeing this issue with a source checkout.

**Comment by noahdesu** [comment]
I added something like this to ycsb.sh where the class path is constructed for the source case and it seems to work. not sure what the best thing is.

```
+  # Core dependencies from Maven
+  CLASSPATH_FILE=$(mktemp)
+  mvn -pl com.yahoo.ycsb:core dependency:build-classpath -Dmdep.outputFile=$CLASSPATH_FILE
+  CLASSPATH_MVN=$(cat $CLASSPATH_FILE)
+  echo XXX $CLASSPATH_MVN
+  CLASSPATH=$CLASSPATH:$CLASSPATH_MVN
 fi
```

**Comment by risdenk** [comment]
@busbey so I had a second look at this. It is simpler to copy the dependencies for `core` and slightly modify the `ycsb.sh` and `yscb.bat` to pick up those dependencies. The parsing of `mvn dependency:build-classpath` isn't easy to do with Windows.

**Comment by risdenk** [comment]
@busbey yea that sounds reasonable. I'll update the PR.

**Comment by manolama** [comment]
@risdenk Still want this in v13?

**Comment by risdenk** [comment]
@manolama up to you. I'm done making changes now unless there are required changes from reviews.

@busbey Can you take a look at the latest changes? I don't have a Windows machine to test on right now. It works on my Mac. I switched from `for` to `ls` since it was easier to read and shouldn't be too many files in the directory that are *.jar.

**Comment by risdenk** [comment]
@busbey that would be great. The tests I ran:

```
mvn clean
bin/ycsb.sh load basic -P workloads/workloada
bin/ycsb.sh load rest -P workloads/workloada
```

This will make sure that basic works and builds correctly. Then check that another binding runs without getting a classpath error.

**Comment by busbey** [comment]
confirmed this didn't get any classpath trouble on Windows 10 Home

```
git clean -xdf
.\bin\ycsb.bat load basic -P .\workloads\workloada
.\bin\ycsb.bat load rest -P .\workloads\workloada
```

**Pull request merged**
