### PR TITLE
Adding Support for GridDB

### PR DESCRIPTION
**Pull request by rbrasga**
Hello,

I recently started using GridDB with YCSB, and I was surprised to see it wasn't part of the primary YCSB git repo.

I have it compiled and running. I realize I may need to make the README more clean and clear, so let me know what needs to be done to get this added to the official YCSB repo.

Thanks,
-Remi

### CODE REVIEW

**Comment by busbey** [comment]
Thanks for your interest!

Is the effort here to directly port the griddb binding from griddb/griddb_ycsb? Or a  reimplementation?

**Comment by rbrasga** [comment]
> Is the effort here to directly port the griddb binding from griddb/griddb_ycsb? Or a reimplementation?

The effort is to directly port the griddb binding. If you are already working with them, then you could ignore this pull request.

I will look into the error and get it resolved.

**Comment by busbey** [comment]
Have you approached the griddb folks about merging in here? I'm hesitant to fork their binding if they're still maintaining it.

**Comment by rbrasga** [comment]
Yes, I have one of the managers sitting across from me. I am waiting for them to get back to me on if they attempted integrating with YCSB previously. (There are other similar plugins they haven’t integrated with the official repository)

**Comment by busbey** [comment]
if you rebase to the current master branch the travis failures will probably be addressed; we just pushed some fixes.

**Comment by busbey** [comment]
obsoleted by #1258

**Pull request closed without merging**
