### PR TITLE
Add rocksdb-binding for ycsb.

### PR DESCRIPTION
**Pull request by cld378632668**
Add rocksdb-binding for ycsb.

This project have been starred by 86 users and forked by 18 users.

The introduce of RocksDB :  its official website and https://github.com/facebook/rocksdb  .

RocksDB: A Persistent Key-Value Store for Flash and RAM Storage

### CODE REVIEW

**Comment by cld378632668** [comment]
The information above show that I have successfully commit (or pull requests) my codes into  brianfrankcooper:master .  
But why I cant see my  rocksdb module , a folder wich should be named rocksdb,  on ycsb:master ?

**Comment by cld378632668** [comment]
What should I do next?

**Comment by cld378632668** [comment]
Can anyone merge this branch with the base branch？

**Comment by busbey** [comment]
Please take a look at #1052 and see if it can meet your needs as is. If not, please provide feedback there or on #1120 and try to come to consensus.

**Comment by busbey** [comment]
hi @cld378632668! did you get a chance to take a look at #1052?

**Comment by busbey** [comment]
#1052 has now merged. If it doesn't address your use case, please submit a new PR that builds upon it.

**Pull request closed without merging**
