### PR TITLE
[core] according to issue #279 RandomByteIterator now generates also …

### PR DESCRIPTION
**Pull request by steffenfriedrich**
…some characters. See #279.

### CODE REVIEW

**Comment by busbey** [comment]
This doesn't help the general problem with BytesIterator in #279. Other workloads could put anything they like in a ByteIterator (as could other data stores) and we should do a better job of turning htings into a String.

Specifically, in ByteIterator we should be using a CharsetDecoder (either for UTF8 or a user configurable encoding that defaults to UTF8). (and similarly if we need to go from String -> byte we should use a CharsetEncoder)

**Comment by steffenfriedrich** [comment]
I see, so I changed the the `toString()` method of the ByteIterator to decode the byte array by using the java.nio.charset. This way the iterator is still be consumed by using its `toArray()` method and additionally the `toString()` method is also faster (according to a microbenchmark I did).

**Comment by busbey** [comment]
The new toString looks great. Why still change the way RandomBytesIterator creates its sequence of bytes?

**Comment by steffenfriedrich** [comment]
Because the old one generated only characters between *space* and *?* (http://www.asciitable.com/). Now the buffer is also filled with some letters because of the `& 63` and `& 95`.

**Comment by steffenfriedrich** [comment]
Should I revert the RandomByteIterator?

**Comment by busbey** [comment]
Sorry, this last week got busy even for me. We just need to confirm the new ranges, I expect it'll be fine. If @gkamat or @cmccoy have time to check it it'll get in sooner.

Eventually I want to change RandomBytesIterator to be random binary (and have a "random printable" or some such for the role the class plays now). But I don't think that burden should fall on this ticket, especially since no one has gone through the ramifications of doing such a change.

**Pull request merged**
