### PR TITLE
[scripts, couchbase] deprecate the old 'couchbase' client in favor of 'couchbase2'.

### PR DESCRIPTION
**Pull request by busbey**
Point folks towards the new couchbase2 client instead of the old one, so we can eventually swap them out.

ping @daschl

### CODE REVIEW

**Comment by daschl** [comment]
@busbey I wonder if we can get rid of it completely because `couchbase2` is backwards compat and can do everything `couchbase` can do?

**Comment by daschl** [comment]
Otherwise if we want to keep it for now then 👍 on the change!

**Comment by busbey** [comment]
If someone who was using the old couchbase module can just swap in the couchbase2 module and use the same configs and talk to the same versions of couchbase2, just removing the old one and deprecating the name "couchbase2" would be fine.

**Comment by daschl** [comment]
hm yeah well okay thats a problem since not the exact same options are supported. then let's keep it deprecated for a couple of versions and remove it at some point. I just brought it up since the 1.4 SDK series in couchbase is EOL right now.. 

the other thing I could look at is somehow supporting the "old" options and converting them to the new ones for backwards compat?

**Comment by busbey** [comment]
probably easier to just deprecate it and pick a time to remove it. I think when we deprecated the old cassandra binding we gave it 6 months.

**Comment by busbey** [comment]
ah, looks like #537 made it three months for cassandra (and we're behind schedule on actually removing).

also I forgot to have this one to put the notice in the README. I'll update the PR later today.

**Comment by daschl** [comment]
👍

**Pull request merged**
