### PR TITLE
[build, core, accumulo, couchbase2, hbase10, orientdb] fixes for jdk9

### LINKED ISSUE #704: build failure running 0.9.0-SNAPSHOT using JDK 9
I used the instructions from Getting Started.

```
git clone git://github.com/brianfrankcooper/YCSB.git
cd YCSB
mvn clean package

```
and got: 

```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project couchbase2-binding: Compilation failure
[ERROR] /Users/larrywhite/IdeaProjects/YCSB/couchbase2/src/main/java/com/yahoo/ycsb/db/couchbase2/Couchbase2Client.java:[674,12] reference to subscribe is ambiguous
[ERROR] both method subscribe(rx.Observer<? super T>) in rx.Observable and method subscribe(rx.Subscriber<? super T>) in rx.Observable match
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :couchbase2-binding

```
my platform:

```
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T07:57:37-04:00)
Java version: 1.9.0-ea, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.9.0.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```

### LINKED ISSUE #705: JDK 9, 10, and 11 support for YCSB
Since JDK 9 is in early access, it would be good to start testing with it and see what changes may be required to support it.

### PR DESCRIPTION
**Pull request by busbey**
* in couchbase2 work around ReactiveX/RxJava#3824
* accumulo test hangs, so skip tests
* hbase10 test crashes with unknown class version, so skip tests
* core jar-with-deps fails, so keep them broken out
* add jdk9 to travis

fixes #704, fixes #705

### CODE REVIEW

**Comment by busbey** [comment]
okay. it looks like JDK9 support is not present in travis-ci yet. To enable the jvm at all we have to move onto some experimental ubuntu hosts in sudo mode, and then maven is known not to work.

So I'd say fixing the current errors are fine, but we can't expect it to consistently work so long as things aren't getting automatically checked.

**Comment by risdenk** [comment]
@busbey JDK 9 isn't GA yet. Still in beta and probably won't be available for a while. Doubt it will be in Travis CI till its GA. Agree that fixing current errors is good. Will review the changes.

**Comment by risdenk** [comment]
I pulled down this PR and tried to run mvn clean package with JDK 9 ea build 113.

OrientDB fails with:

 `Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make member of class com.sun.management.internal.OperatingSystemImpl accessible:  module jdk.management does not export com.sun.management.internal to unnamed module @1a8a8f7c` 

Full output of OrientDB section: https://gist.github.com/risdenk/c055c7cc8cf8d6e8fa966866f613c26b

Solr fails as well with full output here: https://gist.github.com/risdenk/dbe1e28c962a527f1632b4a5e330cf62. To fix the Solr tests, need to update Solr dependencies to Solr 6 which was release about a week ago. There were a few fixes in Solr 6 for JDK 9.

**Comment by risdenk** [comment]
Added #715 and PR #716 to update Solr binding.

**Comment by busbey** [comment]
The OrientDB output looks like we should add the same profile we have for HBase and Accumulo, unless they've since had a release that accounts for JDK9.

**Comment by busbey** [comment]
bump?

**Comment by risdenk** [comment]
@busbey - I don't know much about OrientDB. I would add the same profile for HBase and Accumulo and worry about updating the OrientDB binding later.

**Comment by busbey** [comment]
rebased, updated for asynchbase module, refactored how skipping under jdk9 works so it just requires a property (since we're up to 4 modules). added orientdb and asynchhbase to the set of modules that skip under jdk9.

**Comment by busbey** [comment]
bump?

**Comment by busbey** [comment]
bump? would like to include this before the 0.10.0 release.

**Comment by joshelser** [comment]
Seems reasonable enough to me. Would it help to have someone else also run a build with a jdk9?

**Comment by busbey** [comment]
yep! trying to build with jdk9 would help see how far off of current ea versions we are. But a +1 on the current incremental changes doesn't necessitate such a build. my main criteria when making the change was making sure jdk7 still worked, since it's our release jdk. I haven't updated my jdk9-ea version since starting back in April.

**Comment by busbey** [comment]
bump

**Comment by busbey** [comment]
Bump?

**Comment by risdenk** [comment]
👍

**Pull request merged**
