### PR TITLE
Updating Apache Geode Version to 1.1.0

### PR DESCRIPTION
**Pull request by davinash**
Updating Apache Geode Version to 1.1.0

Relates to #935

### CODE REVIEW

**Comment by risdenk** [comment]
Assuming this is a backwards compatible change? 1.1.0 can use 1.0.0?

**Comment by davinash** [comment]
@risdenk No, Geode 1.1.0 client cannot talk with Geode 1.0.0 Server.

**Comment by davinash** [comment]
Is there anything pending here for merging to master ?

**Comment by risdenk** [comment]
@davinash I just kicked off the CI build again since it timed out for some reason.

What happens if a Geode 1.1.0 client tries to talk to a Geode 1.0.0 server? Does it fail? Any reason the minor versions are not compatible?

**Comment by risdenk** [comment]
@davinash Any update here?

**Comment by davinash** [comment]
Sorry for delayed response 1.1.0 client cannot talk with 1.0.0 server

**Comment by busbey** [comment]
Hi @davinash!

Would folks still reasonably expect the ability to benchmark a Geode 1.0.0 server? If so, we'll need a way to do either 1.1.0 clients or 1.0.0 clients.

In other storage bindings, we deal with incompatible client/server changes by maintaining multiple YCSB clients. For example, Apache HBase 0.94 has been end-of-maintenance for some time but we still maintain clients specific to 0.94 and then later incompatible versions.

**Comment by manolama** [comment]
@davinash Just following up on this one. Since I already potentially screwed up and merged the Geode 1.2.0 update, can you let us know of the status of the project? E.g. is 1.1 the first main-stream release and folks shouldn't be using or benching the 1.0 or pre-1.0 versions? And is 1.2 backwards compatible with 1.1? Thanks.

**Comment by manolama** [comment]
Since I merged the 1.2.0 I'll go ahead and close this.

**Pull request closed without merging**
