### PR TITLE
Added support for Apache Crail (Incubating)

### PR DESCRIPTION
**Pull request by patrickstuedi**

### CODE REVIEW

**Comment by patrickstuedi** [comment]
@busbey Sean, this is an updated PR integrating Crail (crail.apache.org) we discussed last year. Do you think the PR will be merged soon, or are there an missing pieces or issues you would like me to address?

**Comment by patrickstuedi** [comment]
Ok, thanks, I'll should have this ready next week!

**Comment by patrickstuedi** [comment]
The PR is ready for review. 
- Moved the classes to a crail specific package
- Setting table based on properties
- Using logging framework instead of System.out
- Also added one new parameter to control whether or not the keys can be enumerated

**Comment by busbey** [comment]
Thanks for pushing on this again @patrickstuedi

I'll ping you for testing when the next release gets going.

**Pull request merged**
