### PR TITLE
[solr,solr6] Add Solr 6 binding

### LINKED ISSUE #715: Add Solr 6 binding
Solr 6.0.0 was released about a week ago. Solr 6 also has some fixes for JDK 9. Relates to #705

### PR DESCRIPTION
**Pull request by risdenk**
Closes #715

### CODE REVIEW

**Comment by risdenk** [comment]
@busbey can you review? This would help move forward JDK 9 support (#705 and #712)

**Comment by risdenk** [comment]
bump?

**Comment by risdenk** [comment]
bump?

**Comment by risdenk** [comment]
bump?

**Comment by busbey** [comment]
jdk8 was my big question. it looks like compilation with jdk7 is fine, but running (including tests) requires jdk8. Do I have that right?

**Comment by risdenk** [comment]
It should be ok compiling with jdk 7. I haven't tested this locally but it seems to compile in travis with jdk 7. As long as we don't use jdk 8+ things (lambdas,etc) in the client then I think it should be ok. Running (including tests) requires JDK8.

**Comment by risdenk** [comment]
@busbey good catch. I updated the PR with `bin/bindings.properties` updated.

**Comment by risdenk** [comment]
Just checked and YCSB with Solr 6 compiles locally with JDK 7.

**Pull request merged**
