### PR TITLE
Update cassandra2-cql layer to use the new driver version.

### LINKED ISSUE #612: Supporting Cassandra 3.0+
The current cassandra2-cql layer errors when used with new versions of cassandra.
```
$ bin/ycsb run cassandra2-cql -P workloads/workloadc -p hosts=localhost
[WARN]  Running against a source checkout. In order to get our runtime dependencies we'll have to invoke Maven. Depending on the state of your system, this may take ~30-45 seconds
[DEBUG]  Running 'mvn -pl com.yahoo.ycsb:cassandra2-binding -am package -DskipTests dependency:build-classpath -DincludeScope=compile -Dmdep.outputFilterFile=true'
java -cp /Users/m/Desktop/scratch/YCSB/cassandra2/conf:/Users/m/Desktop/scratch/YCSB/cassandra2/target/cassandra2-binding-0.7.0-SNAPSHOT.jar:/Users/m/.m2/repository/io/netty/netty-handler/4.0.27.Final/netty-handler-4.0.27.Final.jar:/Users/m/.m2/repository/org/hdrhistogram/HdrHistogram/2.1.4/HdrHistogram-2.1.4.jar:/Users/m/.m2/repository/io/netty/netty-transport/4.0.27.Final/netty-transport-4.0.27.Final.jar:/Users/m/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.4/jackson-core-asl-1.9.4.jar:/Users/m/.m2/repository/io/netty/netty-buffer/4.0.27.Final/netty-buffer-4.0.27.Final.jar:/Users/m/.m2/repository/io/netty/netty-common/4.0.27.Final/netty-common-4.0.27.Final.jar:/Users/m/.m2/repository/com/datastax/cassandra/cassandra-driver-core/2.1.8/cassandra-driver-core-2.1.8.jar:/Users/m/.m2/repository/org/slf4j/slf4j-api/1.6.4/slf4j-api-1.6.4.jar:/Users/m/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.4/jackson-mapper-asl-1.9.4.jar:/Users/m/.m2/repository/com/codahale/metrics/metrics-core/3.0.2/metrics-core-3.0.2.jar:/Users/m/Desktop/scratch/YCSB/core/target/core-0.7.0-SNAPSHOT.jar:/Users/m/.m2/repository/io/netty/netty-codec/4.0.27.Final/netty-codec-4.0.27.Final.jar:/Users/m/.m2/repository/com/google/guava/guava/14.0.1/guava-14.0.1.jar com.yahoo.ycsb.Client -db com.yahoo.ycsb.db.CassandraCQLClient -P workloads/workloadc -p hosts=localhost -t
YCSB Client 0.1
Command line: -db com.yahoo.ycsb.db.CassandraCQLClient -P workloads/workloadc -p hosts=localhost -t
Loading workload...
Starting test.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:193)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:227)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1409)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:382)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:180)
	... 2 more
com.yahoo.ycsb.DBException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:193)
	at com.yahoo.ycsb.DBWrapper.init(DBWrapper.java:77)
	at com.yahoo.ycsb.ClientThread.run(Client.java:289)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:227)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1409)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:382)
	at com.yahoo.ycsb.db.CassandraCQLClient.init(CassandraCQLClient.java:180)
	... 2 more
[OVERALL], RunTime(ms), 725.0
[OVERALL], Throughput(ops/sec), 0.0
```
Updating the version of the cassandra driver to 3.0.0 fixes this. As per http://datastax.github.io/java-driver/#compatibility, compatibility with older versions should be unaffected.

### PR DESCRIPTION
**Pull request by uluyol**
Fixes #612.

### CODE REVIEW

**Comment by busbey** [comment]
Is this based off of the current master branch? It's getting a bunch of checkstyle errors that I didn't think were active yet for core.

Please update your commit message to start with the impacted module, ie "[cassandra2]"

Should we put this in a new Cassandra 3 module to ensure folks can compare Cassandra 2 to Cassandra 3?

**Comment by uluyol** [comment]
> Is this based off of the current master branch? It's getting a bunch of checkstyle errors that I didn't think were active yet for core.

It is based off the current master.

> Please update your commit message to start with the impacted module, ie "[cassandra2]"

Done

> Should we put this in a new Cassandra 3 module to ensure folks can compare Cassandra 2 to Cassandra 3?

I don't see why that would be necessary. The new driver is backwards compatible (see http://datastax.github.io/java-driver/#compatibility).

**Comment by busbey** [comment]
Sounds good. We'll need to figure out what going on with master before merging this.

**Comment by kruthar** [comment]
@busbey - Travis runs ```mvn test``` which prints out all the checkstyle errors, but they do not halt execution and they are not the reason why Travis is failing.

It looks like there might be an incompatibility in the test class and it needs to be looked at.

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.yahoo.ycsb.db.CassandraCQLClientTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.698 sec <<< FAILURE!
com.yahoo.ycsb.db.CassandraCQLClientTest  Time elapsed: 3.697 sec  <<< ERROR!
java.lang.NoSuchMethodError: com.datastax.driver.core.Cluster$Builder.addContactPoints(Ljava/lang/String;)Lcom/datastax/driver/core/Cluster$Builder;
	at org.cassandraunit.CassandraCQLUnit.load(CassandraCQLUnit.java:42)
	at org.cassandraunit.BaseCassandraUnit.before(BaseCassandraUnit.java:32)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error:
  com.yahoo.ycsb.db.CassandraCQLClientTest: com.datastax.driver.core.Cluster$Builder.addContactPoints(Ljava/lang/String;)Lcom/datastax/driver/core/Cluster$Builder;

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by busbey** [comment]
Good catch! That's what I get for trying to read Travis-CI results on a phone.

**Comment by risdenk** [comment]
I pulled down #614 and updated cassandra unit to 2.2.2.1 and that didn't fix the test errors. Same error with signature mismatch basically. Looks like cassandraunit isn't at 3.x yet so doesn't support the 3.x classes? I don't know if there is an easy way to fix this yet. Do we need to wait for cassandraunit to a release a 3.x?

**Comment by uluyol** [comment]
Cassandra-unit has support for Cassandra 3 now. Unfortunately Cassandra 2.2+ [requires Java 8](https://docs.datastax.com/en/upgrade/doc/upgrade/cassandra/upgradeCassandraDetails.html) which presumably is causing the tests to fail since they work locally. Not sure what to do here.

**Comment by busbey** [comment]
For now, I think the best path is to

1) add a JUnit Assume that limits the Cassandra tests to only run them under JDK8+

2) expand our travis-ci profile to also test one jdk8 (probably Oracle)

3) verify wether or not a _client_ using the Cassandra 3 driver to talk to a Cassandra 2.2+ server has to be using jdk8

4) based on the outcome of 3, update the README  to indicate that folks wanting to test against Cassandra 2.2+ need to run JDK8 (our jdk7 compiled release artifacts should still work fine).

**Comment by nastra** [comment]
Do we already have someone for tackling all of those 4 points? If not, I would take a look at it, because I'd like to get that PR merged sooner than later and use it for testing C* 3.0 with YCSB.

**Comment by risdenk** [comment]
> Do we already have someone for tackling all of those 4 points? If not, I would take a look at it, because I'd like to get that PR merged sooner than later and use it for testing C* 3.0 with YCSB.

@nastra If you are willing to help then go for it. Only number 1 on the list requires modifying this PR. Items 2-4 would be separate PRs it looks like.

@uluyol Can you update the PR to address @busbey's first item about only running the Cassandra 3 test under JDK8+?

**Comment by uluyol** [comment]
I'm not sure how to fix this, it looks like just loading the test causes issues. I don't have much time to work on this so @nastra or whoever else can feel free to take this over.

**Comment by busbey** [comment]
thanks for the work so far @uluyol!

**Comment by busbey** [comment]
I put up #669 to get around the jdk7 incompatibility.

**Comment by busbey** [comment]
Number 1 is taken care of now. @nastra could you take a look at handling numbers 2-4?

**Comment by risdenk** [comment]
@busbey and @nastra I'm going to open new issues for numbers 2-4 and linked them to this. That would allow better tracking.

**Pull request merged**
