### PR TITLE
"entrySet()" should be iterated when both the key and value are needed

### PR DESCRIPTION
**Pull request by kirill-vlasov**
This pull request is focused on resolving occurrences of Sonar rule squid:S2864 - "entrySet()" should be iterated when both the key and value are needed
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2864
Please let me know if you have any questions.
Kirill Vlasov

### CODE REVIEW

**Comment by busbey** [comment]
Please update the commit message to start with the impacted modules: "[core, Cassandra, gemfire, mapkeeper]"

**Comment by allanbank** [comment]
:+1:

**Comment by busbey** [comment]
Could you rebase this to current master please?

**Comment by kirill-vlasov** [comment]
@busbey commit rebased

**Pull request merged**
