### PR TITLE
[s3] Use AWS IOUtils to read object data

### LINKED ISSUE #1019: remove redundant code in S3 binding in favor of IOUtils
from the review of #1010 

```
...
import com.amazonaws.util.IOUtils;
...
// writing the stream to bytes and to results
result.put(key, new ByteArrayByteIterator(IOUtils.toByteArray(objectData)));
objectData.close();
...
```

### PR DESCRIPTION
**Pull request by risdenk**
Fixes #1019 

I don't have a good way to test this but it seems straight forward.

### CODE REVIEW

**Comment by busbey** [comment]
Oh! 5 minutes ago. Lol. Sorry for the quickness there. :)

**Comment by risdenk** [comment]
@busbey chasing it down now. :)

**Comment by risdenk** [comment]
IDE missing the import is always good. Sigh.

**Comment by risdenk** [comment]
oraclejdk7 is having an issue:

```
$ jdk_switcher use oraclejdk7
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle
...
$ mvn install -q -DskipTests=true
Error: JAVA_HOME is not defined correctly.
  We cannot execute /usr/lib/jvm/java-7-oracle/bin/java
```

It is almost like oracle Java 7 doesn't exist.

**Comment by busbey** [comment]
aha! oracle jdk7 doesn't exist!

https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879

**Comment by busbey** [comment]
lemme put up a quick patch

**Comment by risdenk** [comment]
Rebased on top of PR #1022

**Comment by risdenk** [comment]
Thanks @busbey

**Pull request merged**
