### PR TITLE
[couchbase2] Added support for ttl in Couchbase2

### PR DESCRIPTION
**Pull request by kunalsomani**
Time to live (TTL) is the amount of time until a document expires in Couchbase Server. Having this property will help user not to clean up DB manually.

### CODE REVIEW

**Comment by busbey** [comment]
out of all that noise, this is the bit you should care about:

> [ERROR] src/main/java/com/yahoo/ycsb/db/couchbase2/Couchbase2Client.java[96] (sizes) LineLength: Line is longer than 120 characters (found 121).

We do style enforcement on the couchbase2 client, so this will need to get cleaned up.

**Comment by busbey** [comment]
looks reasonable, presuming a TTL of 0 means "never expire" (or whatever the default is when TTL isn't given).

what do you think @daschl?

**Comment by daschl** [comment]
Yes, 0 is the default and means never expire. 

If we could name it `ttl` i'd prefer that, or even `expiry` since thats what the SDK calls it. Other than that I'm good with the change.

**Comment by daschl** [comment]
@kunalsomani can you please just name it "expiry"? I don't like object, since the naming talks about documents, not objects :) .. sorry to be nitpicky but I think its important for usability

**Comment by kunalsomani** [comment]
Name with expiry makes it difficult to understand to user about the system property, "couchbase.expiry" does not say about the document expiry property. We should have meaningful property so that user can understand about it. I chose this property as YCSB is using the similar property in memcached "memcached.objectExpirationTime" but with bigger name :)

Let me know your feedback and will change if required.

**Comment by daschl** [comment]
@kunalsomani okay, then what about `couchbase.documentExpiry` ?

**Comment by kunalsomani** [comment]
ping @daschl

**Comment by daschl** [comment]
looks good to me now, thanks! :)

**Comment by busbey** [comment]
the jdk8 build failed due to cassandra. restarted it.

thanks for the review @daschl!

**Comment by kunalsomani** [comment]
@busbey  Can we merge this change? Jdk8 Build failed because of Cassandra.

**Comment by busbey** [comment]
I'm trying to get a clean CI run. The Cassandra test has historically been finicky, but other PRs are passing it.

**Pull request merged**
