### PR TITLE
[rocksdb] add rocksdb.optionsfile property

### PR DESCRIPTION
**Pull request by twblamer**
This adds support to run RocksDB with a custom [options file](https://github.com/facebook/rocksdb/wiki/RocksDB-Options-File).

This also updates the RocksDB Maven artifact version to the latest (6.2.2).

### CODE REVIEW

**Comment by busbey** [comment]
If I have a data file for rocksdb written by version 5, will it still work when I run with the version 6 library?

**Comment by twblamer** [comment]
From looking at the Rocks [compatibility strategy](https://github.com/facebook/rocksdb/wiki/RocksDB-Compatibility-Between-Different-Releases) and the [release log](https://github.com/facebook/rocksdb/releases), I don't anticipate any breaking issues moving from 5.11.3 to 6.2.2. Especially since YCSB is currently initializing the RocksDB options using the `optimizeForLevelCompaction()` helper function and will continue doing so by default, so any DB initialized by YCSB shouldn't depend on any exotic options that got deprecated.

I just tested it myself to confirm (loaded a YCSB DB with 100K records using Rocks 5.11.2, rebuilt YCSB with Rocks 6.2.2 and ran a run workload with no issues).

However, my knowledge of RocksDB internals is minimal, so It would be could if @adamretter or another Rocks maintainer could chime in.

**Comment by adamretter** [comment]
@twblamer I think the version upgrade should be fine.

**Comment by twblamer** [comment]
Fixed a typo and squashed commits.

**Comment by twblamer** [comment]
@adamretter Does the PR look OK to you?

**Comment by adamretter** [comment]
@twblamer It would be good to see a test case.

**Comment by twblamer** [comment]
@adamretter I've added a test, please have a look.

**Pull request merged**
