### PR TITLE
[couchbase2] logical error in decode()

### PR DESCRIPTION
**Pull request by WindzCUHK**
When dataintegrity=true, no field values in passed to verifyRow() for verify and keep on getting error.

### CODE REVIEW

**Comment by busbey** [comment]
this looks correct to me. mind taking a quick look @daschl ?

**Comment by daschl** [comment]
yup makes sense

**Comment by busbey** [comment]
@daschl should I cherry-pick this into the upcoming 0.10.0-staging branch? It'll mean we'll need couchbase testing for #772.

**Comment by daschl** [comment]
yes merge it please, I can do the testing for 0.10

**Comment by daschl** [comment]
@busbey but if we do the testing can you please please also cherry-pick https://github.com/brianfrankcooper/YCSB/commit/5edb1d9e2c9e51ec1ea26e1504305a7090653787 over? Thanks!

**Comment by busbey** [comment]
I think that commit requires the SDK update too? Can we take this discussion over to #772?

**Comment by daschl** [comment]
@busbey this commit introduced a regression, fixing it right now.

**Pull request merged**
