### PR TITLE
[mongodb] update parameter for connection url to match previous behavior and docs.

### PR DESCRIPTION
**Pull request by saggarsunil**
[mongodb] update parameter for connection url to match previous behavior and docs.

Changes:
1. mongodb configuration parameter bug (mongodb.url)
    Even though the documentation mentioned mongodb.url, the code was expecting mongodatabase.url property. Modified the code and comments in code to point to correct link.

2. README file change
    Default DB is 'ycsb'
3. Some cleanup.

### CODE REVIEW

**Comment by busbey** [comment]
could you update the commit message to have a first line that matches the new subject line for this pull request?

**Comment by saggarsunil** [comment]
Done.

**Comment by busbey** [comment]
I don't see the updated changes, can you try pushing them again?

**Comment by saggarsunil** [comment]
Done.

**Comment by busbey** [comment]
@allanbank you good for this on 0.2.0?

**Comment by allanbank** [comment]
@saggarsunil Can you update the AsyncMongoDbClient too? I think the only change is to switch the body if this [If block](https://github.com/brianfrankcooper/YCSB/blob/master/mongodb/src/main/java/com/yahoo/ycsb/db/AsyncMongoDbClient.java#L202) to default the database to ycsb.

**Comment by saggarsunil** [comment]
@allanbank Made the changes.

**Comment by allanbank** [comment]
@saggarsunil - Thanks.  Looks great.

@busbey - I would like to see this in 0.2.0, if possible.

**Comment by busbey** [comment]
Sure thing. Thanks for reviewing, I'll pull this in tonight and make a new
RC.

**Pull request merged**
