### PR TITLE
Port ycsb to Python3 and also make it Python2 compatible

### PR DESCRIPTION
**Pull request by adonis0147**
Python2 has reached EOL, so we should port the ycsb to Python3.
The modification also makes the ycsb Python2 compatible.

### CODE REVIEW

**Comment by KFilipek** [comment]
Is it the same code as #1405?

**Comment by sarkarsaurabh27** [comment]
Is someone planning to merge this?

**Comment by adonis0147** [comment]
@busbey PTAL.

**Comment by busbey** [comment]
I am planning to merge 1 of the several python updates.

**Comment by RudraNirvan** [comment]
@busbey what's the ETA for this Python 3 update?

**Comment by busbey** [comment]
providing a review will reduce the time it takes me to merge  things.

**Comment by agniramadani** [comment]
I am trying to load the data:
bin/ycsb load ignite -p hosts="10.0.0.1" -s -P workloads/workloada -threads 4 -p operationcount=100000 -p recordcount=100000 > output-ignite.txt

But I am encountering this issue:
2022-05-20 16:50:41:010 10 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2022-05-20 16:50:51:010 20 sec: 0 operations; est completion in 106751991167300 days 15 hours 
2022-05-20 16:51:01:010 30 sec: 0 operations; est completion in 106751991167300 days 15 hours

**Review by fruch — APPROVED** [review]
LGTM

**Review by uscxiexing — APPROVED** [review]

**Comment by aseering** [comment]
I'm excited about Py3 support!  Is there anything that I or others could do to contribute / help it along?  There's an ask for a review in the comments above, and a subsequent LGTM and approval.

**Comment by robert-s-lee** [comment]
will be great to have this merged.  what is needed for the review?

**Review by prasannasvenkat — APPROVED** [review]

**Comment by karim-manaouil** [comment]
Can you please merge this?

**Comment by karim-manaouil** [comment]
Two months and no updates on this!! No Linux distro is shipping Python2, folks! Come on, please!!

**Comment by honggyukim** [comment]
Yeah, please merge this. I have also tested this patch works fine with python3.

**Comment by busbey** [comment]
Thanks for the contribution.

**Review by busbey — COMMENTED** [review]
👍

**Comment by cindy-peng** [comment]
Hi @busbey, the latest package release YCSB 0.17.0 was from October 2019. Is there any plan to make a new release and include this Python3 support?

**Pull request merged**
