### PR TITLE
[cassandra2]add sigar dependency in test scope and add tracing function

### PR DESCRIPTION
**Pull request by jixuan1989**
This pull request is a modification from  #776, while in this PR, 
1. I set the sigar-dist dependency as test scope. 
2. I clean the commit logs and simplify them.
(both of them are suggested by @busbey )

### CODE REVIEW

**Comment by busbey** [comment]
please force-push over the branch for #776 instead of creating a new PR.

**Comment by jixuan1989** [comment]
@busbey  Hm... I am sorry I am not an expert of Git. I feel confused about "force-push over the branch for..", what do you mean about "force-push"? Like this? 

1. Modify the pom.xml file.

2. `git add pom.xml`; git commit -m "comments.."

3. `git push --force  myRemoteURL myBranchName`

If so, when I push a modification to the branch (no matter whether I use --force or not), I think  a new commit-id will be generated, while the PR of #776 does not changes...

**Comment by busbey** [comment]
ah. sorry I missed this comment over here.

the branch on your github for PR #776 is named 'cassandra-tracing-function'. even if the commit-ids change, github will associate the PR with the branch-name rather than the commit-ids.

I'm not sure if git force pushing works with a full remote url and branch name, I'm used to using a remote name (very often 'origin') and branch name.

**Comment by jixuan1989** [comment]
That's ok. Thank you for your comments. I made it!!

**Pull request closed without merging**
