### PR TITLE
Update ycsb python wrapper

### PR DESCRIPTION
**Pull request by Sraw**
This wrapper has been updated to be Python2-Python3 compatible.
And the Python2.6 supported has been removed as it is almost impossible to be used.

### CODE REVIEW

**Comment by Sraw** [comment]
I've never gone into that run from source branch honestly. It should work for both two branches now. Tested on my laptop.

**Comment by busbey** [comment]
Thanks for the update!

**Comment by busbey** [comment]
ah geez. it looks like this closed automatically when I made the 0.16.0 release and I totally didn't notice. my apologies!

I need to figure out which of the three attempts at python 3 support we adopt and then move forward with one. I'll keep this one in the running.

**Comment by busbey** [comment]
favoring #1421 instead

**Pull request closed without merging**
