### PR TITLE
[couchbase2] Update Java SDK version, query for workloade

### PR DESCRIPTION
**Pull request by ingenthr**
This PR has a dependency update.

Atop that, there's a change to the query to use RAW results.  More in the commit message there.

### CODE REVIEW

**Comment by ingenthr** [comment]
I looked at the build check, it seems to be a missing dependency from the cassandra binding?  I don't think it's related to my change.

**Comment by daschl** [comment]
@busbey what do you think? I'm 👍  on the change :)

**Comment by busbey** [comment]
Let's retry the build failures and make sure it's just flakeys

**Comment by ingenthr** [comment]
Woo, pass that time @busbey !

**Comment by ingenthr** [comment]
Thanks @busbey !

**Pull request merged**
