### PR TITLE
Source files should not have any duplicated blocks

### PR DESCRIPTION
**Pull request by kirill-vlasov**
This pull request is focused on resolving occurrences of Sonar rule common-java:DuplicatedBlocks - Source files should not have any duplicated blocks
You can find more information about the issue here:
https://dev.eclipse.org/sonar/coding_rules#q=common-java:DuplicatedBlocks
Please let me know if you have any questions.
Kirill Vlasov

### CODE REVIEW

**Comment by bigbes** [comment]
Tarantool part look OK

**Comment by kirill-vlasov** [comment]
Checkstyle issues are fixed

**Comment by busbey** [comment]
Changes look fine to me.

@allanbank do you have a chance to take a look at the mongo part?

@ivanB1975 could you check out the s3 refactoring?

**Comment by busbey** [comment]
@kirill-vlasov would you mind rebasing this to the current master branch?

**Comment by kirill-vlasov** [comment]
@busbey commit rebased

**Comment by ivanB1975** [comment]
@Busbey sorry for the delay, I checked it. All fine, I only get the message for each client: DBWrapper: report latency for each error is false and specific error codes to track for latency are: []
But I guess it is not important.

**Pull request merged**
