### PR TITLE
Fix HashMap (gh-353) bug

### PR DESCRIPTION
**Pull request by bigbes**
and refactor *measurement* files

### CODE REVIEW

**Comment by cmatser** [comment]
I noticed the following code in Measurements.java starting on line 133:
```java
  static class StartTimeHolder {
    long time;

    long startTime(){
      if(time == 0) {
        return System.nanoTime();
      }
      else {
        return time;
      }
    }
  }
```

While I don't doubt the code is working, I normally see methods like this set starting values in the initialize case.  I just want to point this out in case this was intended.

So, the change I would recommend would be:
```java
  static class StartTimeHolder {
    long time;

    long startTime(){
      if(time == 0) {
        time = System.nanoTime();
      }
      return time;
    }
  }
```

Chrisjan

**Comment by bigbes** [comment]
@cmatser it wasn't intended, but i didn't modify this kind of constructions, before this project has strict format guidelines..

**Comment by cmatser** [comment]
@bigbes Ah, sorry.  I saw it in the green section and thought it was new code.  I see now that it was just carried forward.  Thanks for clarifying.

**Comment by busbey** [comment]
Looks good to me. What do you think @cmatser? Ready to merge?

**Comment by cmatser** [comment]
@busbey Ready!

Do you know if there is a way for the web view diff to ignore whitespace?  So, when I click on the "Files changed" tab for this PR, I can reduce some of the noise caused by whitespace changes.

**Comment by busbey** [comment]
I believe you can add "?w=1" to the URL

**Comment by cmatser** [comment]
Yes!  That made my day!!!  :)

**Comment by bigbes** [comment]
Any chance to merge this?

**Comment by nitsanw** [comment]
@cmatser Your change suggestion to StartTimeHolder changes the behaviour of the method. In the original, if startTime is never set repeated calls to getStartTime will return __different__ values based on System.nanotime(). In you version the first call will set the startTime and it will stay at that value until someone resets it.
This is not to say that this is not confusing code which can do with some love, but the refactoring you propose needs further refining

**Comment by cmatser** [comment]
@nitsanw  Agreed.  I wanted to point it out in case that was an unintentional side-effect.

**Pull request merged**
