### PR TITLE
[orientdb] fixed end table scan issue

### PR DESCRIPTION
**Pull request by kruthar**
This fixes the end table scanning brought up in #562.

While working on this I found some things that should probably be marked as known issues.

1. First is a performance issue, after testing with a few different recordcounts I found that iterateEntriesMajor() return time is directly linked with number of records in the table. So, a relatively small scan size will start to perform worse on larger tables. The better solution would have been to use iterateEntriesBetween(), problem is it takes a start and end key which is not how the current scan framework is set up. It may be a good idea to think about updating the scan operation to pass a recordcount as well as a corresponding endkey. This would benefit more bindings then OrientDB I believe. There are a few things that complicate that idea, but I'll save that for that discussion.
2. The OIndexCursor implementation used here seems to be broken. It does not track the entries properly when iterating so when you get to the end of the iterator you get a ```NullPointerException```. For more info on why, here is the issue I posted: https://github.com/orientechnologies/orientdb/issues/5541. With a sufficiently high recordcount, +10000, this doesn't happen too often. I choose to not try and catch it, you never know if a legitimate null will pop up sometime. False negatives seemed better to me then false positives.

Should known issues go into the orientdb README? anywhere else?

### CODE REVIEW

**Comment by busbey** [comment]
The orientdb readme sounds like the right place.

**Comment by kruthar** [comment]
OK, added issues to README. Subsequently fixed the README issue in #539.

**Comment by busbey** [comment]
+1. We should probably request this get cherry picked to 0.6.0's staging branch.

**Comment by kruthar** [comment]
I'm good either way, I have a couple more PR's coming for orientdb, as well as @allanbank's checkstyle PR which still needs to be merged. Hopefully the orient db can join the tested list by the next release.

**Pull request merged**
