### PR TITLE
updated ArangoDB binding (Java driver 4.4.1)

### PR DESCRIPTION
**Pull request by mpv1989**
Updated arangodb binding with Java driver 4.4.1. This version is compatible with ArangoDB version 2.7 up to current 3.3. I also removed binding `arangodb3` from PR #903 because it is not needed anymore.

### CODE REVIEW

**Comment by busbey** [comment]
Does this need to be included in the 0.14.0 release (#1117) for ArangoDB to work?

Should we include it to avoid a depreciation cycle for removing the arangodb3 binding?

**Comment by mpv1989** [comment]
There is no need of including it in 0.14.0 release. Both bindings `arangodb` and `arangodb3` will still work in the current stage with current ArangoDB versions. I just wanted to clean things up and get rid of this ugly `arangodb3` binding.

**Comment by busbey** [comment]
Hi @mpv1989! I'm going to start rolling the next release soon. Do you have the time to add in the deprecation warning and placeholder for the `arangodb3` binding?

**Comment by mpv1989** [comment]
Hi @busbey,
I'll try to take time for it today

**Comment by mpv1989** [comment]
@busbey done

**Comment by busbey** [comment]
thanks!

**Pull request merged**
